// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN0A9nolpJ163JL4GLX3LDdcrywyvXshA',
    appId: '1:732229593672:web:ccb943f777c8066309067d',
    messagingSenderId: '732229593672',
    projectId: 'event-80003',
    authDomain: 'event-80003.firebaseapp.com',
    storageBucket: 'event-80003.firebasestorage.app',
    measurementId: 'G-BETMXCRLJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARR1hkQa_neT4LwPi_TSb8ROjCplehDvg',
    appId: '1:732229593672:android:315712239f61bd3909067d',
    messagingSenderId: '732229593672',
    projectId: 'event-80003',
    storageBucket: 'event-80003.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhtzugn5ZU2H1zRGWUloOoIJhXyS1KLpI',
    appId: '1:732229593672:ios:be995f38f27f656809067d',
    messagingSenderId: '732229593672',
    projectId: 'event-80003',
    storageBucket: 'event-80003.firebasestorage.app',
    iosBundleId: 'com.example.event',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhtzugn5ZU2H1zRGWUloOoIJhXyS1KLpI',
    appId: '1:732229593672:ios:be995f38f27f656809067d',
    messagingSenderId: '732229593672',
    projectId: 'event-80003',
    storageBucket: 'event-80003.firebasestorage.app',
    iosBundleId: 'com.example.event',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN0A9nolpJ163JL4GLX3LDdcrywyvXshA',
    appId: '1:732229593672:web:a1682681c655404409067d',
    messagingSenderId: '732229593672',
    projectId: 'event-80003',
    authDomain: 'event-80003.firebaseapp.com',
    storageBucket: 'event-80003.firebasestorage.app',
    measurementId: 'G-QLKZLG1DKL',
  );
}
